name: Test PR

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  lint_types:
    runs-on: ubuntu-latest
    name: Typechecking
    steps:
      - uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependecies
        run: yarn install --frozen-lockfile

      - name: Run Typechecker
        run: yarn lint:type

  lint_es:
    runs-on: ubuntu-latest
    name: Lint ESLint
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependecies
        run: yarn install --frozen-lockfile

      - name: Run Eslint
        run: yarn lint:es

  lint_style:
    runs-on: ubuntu-latest
    name: Lint Stylelint
    steps:
      - uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependecies
        run: yarn install --frozen-lockfile

      - name: Run Stylelint
        run: yarn lint:style
